spring:
  datasource:
    url: ${AUTHZ_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${AUTHZ_DATASOURCE_USERNAME}
    password: ${AUTHZ_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
