insert into role(code, name, privileged) values
    ('GENERAL_BANK_USER', 'General bank user', false),
    ('RELATIONSHIP_MANAGER', 'Relationship manager', false),
    ('PARTNER_SR', 'Insurer sales representative', false),
    ('PARTNER_MANAGER', 'Insurer hierarchy manager', false),
    ('PARTNER_ADMIN', 'Insurer administrator', true),
    ('BANK_ADMIN', 'Bank identity administrator', true),
    ('OPERATIONS', 'Bank operations', true);

insert into permission(code, description, regulated) values
    ('lead.create', 'Create a lead', false),
    ('lead.read', 'Read an eligible lead', false),
    ('lead.assign', 'Assign a lead', false),
    ('lead.share_partner', 'Share a lead with its insurer partner', false),
    ('lead.revoke_partner', 'Revoke insurer-partner lead visibility', false),
    ('suitability.perform', 'Perform suitability analysis', false),
    ('quote.create', 'Create an insurance quote', false),
    ('quote.compare', 'Compare insurance quotes', false),
    ('proposal.create', 'Create a proposal', true),
    ('proposal.submit', 'Submit a proposal to the insurer', true),
    ('proposal.view', 'View a proposal', false),
    ('policy.view', 'View policy details', false),
    ('policy.download', 'Download a policy document', false),
    ('partner_user.create', 'Submit a partner-user creation request', false),
    ('partner_user.bulk_import', 'Submit a partner-user bulk import', false),
    ('partner_user.disable', 'Disable a partner user', false),
    ('role.assign', 'Assign a role', false),
    ('entitlement.grant', 'Grant a scoped entitlement', false),
    ('entitlement.deny', 'Create a scoped denial', false),
    ('break_glass.approve', 'Approve break-glass access', false),
    ('audit.read', 'Read authorization audit evidence', false),
    ('report.branch.read', 'Read branch-scoped reports', false),
    ('report.insurer.read', 'Read insurer-scoped reports', false);

insert into role_permission(role_code, permission_code) values
    ('GENERAL_BANK_USER', 'lead.create'),
    ('GENERAL_BANK_USER', 'lead.read'),
    ('GENERAL_BANK_USER', 'suitability.perform'),
    ('GENERAL_BANK_USER', 'quote.create'),
    ('GENERAL_BANK_USER', 'quote.compare'),
    ('RELATIONSHIP_MANAGER', 'lead.create'),
    ('RELATIONSHIP_MANAGER', 'lead.read'),
    ('RELATIONSHIP_MANAGER', 'lead.assign'),
    ('RELATIONSHIP_MANAGER', 'lead.share_partner'),
    ('RELATIONSHIP_MANAGER', 'lead.revoke_partner'),
    ('RELATIONSHIP_MANAGER', 'suitability.perform'),
    ('RELATIONSHIP_MANAGER', 'quote.create'),
    ('RELATIONSHIP_MANAGER', 'quote.compare'),
    ('RELATIONSHIP_MANAGER', 'proposal.create'),
    ('RELATIONSHIP_MANAGER', 'proposal.submit'),
    ('RELATIONSHIP_MANAGER', 'proposal.view'),
    ('RELATIONSHIP_MANAGER', 'policy.view'),
    ('RELATIONSHIP_MANAGER', 'policy.download'),
    ('PARTNER_SR', 'lead.read'),
    ('PARTNER_SR', 'proposal.create'),
    ('PARTNER_SR', 'proposal.submit'),
    ('PARTNER_SR', 'proposal.view'),
    ('PARTNER_MANAGER', 'lead.read'),
    ('PARTNER_MANAGER', 'proposal.view'),
    ('PARTNER_MANAGER', 'report.insurer.read'),
    ('PARTNER_ADMIN', 'partner_user.create'),
    ('PARTNER_ADMIN', 'partner_user.bulk_import'),
    ('PARTNER_ADMIN', 'partner_user.disable'),
    ('PARTNER_ADMIN', 'report.insurer.read'),
    ('BANK_ADMIN', 'partner_user.create'),
    ('BANK_ADMIN', 'partner_user.bulk_import'),
    ('BANK_ADMIN', 'partner_user.disable'),
    ('BANK_ADMIN', 'role.assign'),
    ('BANK_ADMIN', 'entitlement.grant'),
    ('BANK_ADMIN', 'entitlement.deny'),
    ('BANK_ADMIN', 'break_glass.approve'),
    ('BANK_ADMIN', 'audit.read'),
    ('OPERATIONS', 'lead.read'),
    ('OPERATIONS', 'lead.assign'),
    ('OPERATIONS', 'proposal.view'),
    ('OPERATIONS', 'report.branch.read');
