package com.bank.insurance.onesb.observability;

import com.bank.common.audit.AuditActions;
import com.bank.common.audit.AuditEvent;
import com.bank.common.audit.AuditOutcomes;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * WS-1 Phase 4 exit criterion <b>4.4</b> — generates the log samples Compliance reviews.
 *
 * <p>A compliance review of "log samples" is worthless if the samples were written by hand into
 * a document: the reviewer would be approving prose, and the code could diverge from it the
 * same afternoon. These samples are produced by the real {@link LoggingAuditEventPublisher} and
 * the real {@link PiiMasker}, from fixed inputs, and the generated file is compared against the
 * committed one. If masking behaviour changes, this test fails and the compliance pack has to be
 * re-reviewed — which is the correct consequence.
 *
 * <p>Inputs are fixed (no {@code Instant.now()}, no random ids) so the output is byte-stable and
 * a diff means a real behavioural change rather than a new timestamp.
 *
 * <p>Regenerate after an intentional change:
 * <pre>{@code
 * ./gradlew :services:1sb-integration-service:test \
 *     --tests '*AuditLogSampleTest' -DupdateAuditSamples=true
 * }</pre>
 */
@Tag("unit")
@Tag("COMP-002")
class AuditLogSampleTest {

    private static final String SAMPLES =
            "docs/1sb-insurance-integration/service-ssot/compliance/audit-log-samples.md";

    private static final Instant T0 = Instant.parse("2026-08-13T09:15:00Z");
    private static final String JOURNEY = "journey-7f3a";
    private static final String TRACE = "3d9a1c4e8b2f4a17";

    /** A realistic Term proposal body — every field here is PII a reviewer will look for. */
    private static final String PROPOSAL_BODY = """
            {
              "applicationNo": "APP-2026-0417",
              "proposer": {
                "firstName": "Asha",
                "lastName": "Rao",
                "dob": "1990-01-15",
                "pan": "ABCDE1234F",
                "mobile": "9876543210",
                "email": "asha.rao@example.com"
              },
              "nominee": { "name": "Ravi Rao", "dob": "2015-06-02" },
              "sumAssured": 5000000
            }
            """;

    @Test
    void auditSamplesMatchTheCommittedCompliancePack() throws Exception {
        String generated = render();
        Path committed = repoRoot().resolve(SAMPLES);

        if (Boolean.getBoolean("updateAuditSamples")) {
            Files.createDirectories(committed.getParent());
            Files.writeString(committed, generated, StandardCharsets.UTF_8);
            return;
        }

        assertThat(committed)
                .as("audit log samples are missing — regenerate with -DupdateAuditSamples=true")
                .exists();
        assertThat(Files.readString(committed, StandardCharsets.UTF_8))
                .as("""
                        The committed audit log samples no longer match what the code produces.

                        If the change is intentional, regenerate and commit:
                          ./gradlew :services:1sb-integration-service:test \\
                              --tests '*AuditLogSampleTest' -DupdateAuditSamples=true

                        Then flag it: Compliance reviewed the previous samples under criterion
                        4.4, so a change in masking or audit content needs re-review.
                        """)
                .isEqualTo(generated);
    }

    /** The guarantee Compliance is actually being asked to accept. */
    @Test
    void noSamplePayloadLeaksPlaintextPii() {
        String masked = PiiMasker.maskJson(PROPOSAL_BODY);

        assertThat(masked)
                .doesNotContain("ABCDE1234F")
                .doesNotContain("9876543210")
                .doesNotContain("asha.rao@example.com")
                .doesNotContain("1990-01-15")
                .doesNotContain("Asha")
                .doesNotContain("Rao");
    }

    // -------------------------------------------------------------------------------------

    private static String render() {
        List<String> lines = new ArrayList<>();
        for (AuditEvent event : journeyEvents()) {
            lines.add(format(event));
        }

        return """
                # Audit log samples — Term journey

                <!-- GENERATED by AuditLogSampleTest. Do not edit by hand.
                     Regenerate: ./gradlew :services:1sb-integration-service:test \\
                                     --tests '*AuditLogSampleTest' -DupdateAuditSamples=true -->

                Produced by the real `LoggingAuditEventPublisher` and `PiiMasker` from fixed
                inputs, so this file changes only when behaviour changes. Criterion 4.4 evidence.

                ## 1. One Term journey, as it appears in the audit log

                Every line below is what an operator or auditor would actually see. Note what is
                absent: no name, no PAN, no mobile, no email, no date of birth, and no raw
                upstream payload. Outbound calls carry a SHA-256 hash of the **masked** body, so
                two identical submissions are provably identical without either being readable.

                ```text
                %s
                ```

                ## 2. What a proposal body looks like before and after masking

                This is the payload that would otherwise reach a log or an audit hash.

                **Before** (never written anywhere in this form):

                ```json
                %s
                ```

                **After `PiiMasker.maskJson`** — this is what the service is willing to expose:

                ```json
                %s
                ```

                Field-level behaviour, exercised by `PiiMaskerTest`:

                | Input | Masked | Rule |
                |---|---|---|
                | `Asha` | `%s` | First initial only |
                | `9876543210` | `%s` | Last 4 digits retained for support lookups |
                | `asha.rao@example.com` | `%s` | Local part and domain both reduced |
                | `ABCDE1234F` | `%s` | Last 5 retained; leading letters replaced with `*` so the result cannot match a PAN pattern |
                | `1990-01-15` | `%s` | Date of birth removed entirely |

                ## 3. Free-text masking

                PII does not only arrive in known field names. An error message or a nested
                string is pattern-scanned as well:

                ```text
                in : %s
                out: %s
                ```
                """.formatted(
                String.join("\n", lines),
                PROPOSAL_BODY.strip(),
                prettyish(PiiMasker.maskJson(PROPOSAL_BODY)),
                PiiMasker.maskName("Asha"),
                PiiMasker.maskMobile("9876543210"),
                PiiMasker.maskEmail("asha.rao@example.com"),
                PiiMasker.maskPan("ABCDE1234F"),
                PiiMasker.maskDob("1990-01-15"),
                "Rejected for proposer ABCDE1234F (contact 9876543210, asha.rao@example.com)",
                PiiMasker.maskText(
                        "Rejected for proposer ABCDE1234F (contact 9876543210, asha.rao@example.com)"));
    }

    /** The audit events a single Term journey emits, in order. */
    private static List<AuditEvent> journeyEvents() {
        List<AuditEvent> events = new ArrayList<>();

        events.add(base(AuditActions.QUOTE_JOB_CREATED, "QUOTE_JOB", "job-quote-9a1", T0)
                .actorId("rm-4471").actorType("USER")
                .metadata("lob", "TERM")
                .metadata("sumAssured", "5000000")
                .build());

        events.add(base(AuditActions.ONESB_OUTBOUND_CALL, "ONESB_HTTP",
                "/insurance/lifeterm/v1/quote", T0.plusMillis(140))
                .actorId("1sb-integration-service").actorType("SERVICE")
                .metadata("operation", "POST /insurance/lifeterm/v1/quote")
                .metadata("latencyMs", "138")
                .metadata("upstreamHttpStatus", "200")
                .metadata("requestHash", hashOfMasked())
                .build());

        events.add(base(AuditActions.QUOTE_COMPLETED, "QUOTE_JOB", "job-quote-9a1",
                T0.plusSeconds(3))
                .actorId("system").actorType("SYSTEM")
                .metadata("offerCount", "3")
                .metadata("partialErrorCount", "0")
                .metadata("status", "COMPLETED")
                .build());

        events.add(base(AuditActions.PROPOSAL_SUBMITTED, "PROPOSAL_JOB", "job-prop-2c8",
                T0.plusSeconds(95))
                .actorId("rm-4471").actorType("USER")
                .metadata("applicationNumber", "APP-2026-0417")
                .metadata("consentRef", "consent-5521")
                .build());

        events.add(base(AuditActions.CONSENT_REF_MISSING, "PROPOSAL_JOB", "job-prop-3d9",
                T0.plusSeconds(96))
                .actorId("rm-4471").actorType("USER")
                .outcome(AuditOutcomes.FAILURE)
                .metadata("note", "consentRef absent — soft gate, submission allowed")
                .build());

        events.add(base(AuditActions.PAYMENT_URL_RETRIEVED, "PAYMENT_SESSION", "sess-77b",
                T0.plusSeconds(150))
                .actorId("rm-4471").actorType("USER")
                .metadata("applicationNumber", "APP-2026-0417")
                .metadata("amountToBePaid", "4200")
                .build());

        events.add(base(AuditActions.APPLICATION_STATUS_CHECKED, "APPLICATION",
                "APP-2026-0417", T0.plusSeconds(3600))
                .actorId("rm-4471").actorType("USER")
                .metadata("bankStatus", "UW_IN_PROGRESS")
                .build());

        return events;
    }

    private static AuditEvent.AuditEventBuilder base(String action, String resourceType,
                                                     String resourceId, Instant at) {
        return AuditEvent.builder()
                .eventId("evt-" + Integer.toHexString(action.hashCode() & 0xffff))
                .timestamp(at)
                .action(action)
                .resourceType(resourceType)
                .resourceId(resourceId)
                .outcome(AuditOutcomes.SUCCESS)
                .lob("TERM")
                .journeyId(JOURNEY)
                .distributorId("BCIBL")
                .agentId("109337")
                .traceId(TRACE);
    }

    /** Mirrors the format string in {@link LoggingAuditEventPublisher}. */
    private static String format(AuditEvent event) {
        return ("%s  audit eventId=%s action=%s outcome=%s resourceType=%s resourceId=%s "
                + "actorId=%s journeyId=%s traceId=%s metadata=%s")
                .formatted(
                        event.getTimestamp(), event.getEventId(), event.getAction(),
                        event.getOutcome(), event.getResourceType(), event.getResourceId(),
                        event.getActorId(), event.getJourneyId(), event.getTraceId(),
                        event.getMetadata());
    }

    private static String hashOfMasked() {
        try {
            java.security.MessageDigest digest = java.security.MessageDigest.getInstance("SHA-256");
            byte[] out = digest.digest(
                    PiiMasker.maskJson(PROPOSAL_BODY).getBytes(StandardCharsets.UTF_8));
            return java.util.HexFormat.of().formatHex(out);
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

    /** Line-wraps the masked JSON so the compliance pack stays readable. */
    private static String prettyish(String json) {
        try {
            com.fasterxml.jackson.databind.ObjectMapper mapper =
                    new com.fasterxml.jackson.databind.ObjectMapper();
            return mapper.writerWithDefaultPrettyPrinter()
                    .writeValueAsString(mapper.readTree(json));
        } catch (IOException e) {
            return json;
        }
    }

    private static Path repoRoot() {
        Path dir = Paths.get("").toAbsolutePath();
        while (dir != null && !Files.exists(dir.resolve("settings.gradle.kts"))) {
            dir = dir.getParent();
        }
        if (dir == null) {
            throw new IllegalStateException("repository root not found");
        }
        return dir;
    }
}
