# Production — PostgreSQL
spring:
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.bank.persistence: INFO
